jwt:
  issuer: "mybooks.service.user"
  algorithm: "HS256"
  is-symmetric: true

  # this should be in env of course
  private-key: "strong shared password"
  service-token:
    expires-in-seconds: 60

service:
  discovery:
    announce-addr: "vertx.discovery.announce"
    usage-addr: "vertx.discovery.usage"
  user:
    discovery:
      base-name: "mybooks.service.user"
      user-login: "/user-login"
      user-logout: "/user-logout"
  auth:
    discovery:
      base-name: "mybooks.service.auth"
      get-user-token: "/get-user-token"
      refresh-user-token: "/refresh-user-token"

http:
  host: "localhost"
  port: 8096
  err-details-envs:
    - test
    - dev

db:
  mongo:
    db-name: "mybooksUserDb"
    host: "localhost"
    port: 27017
    min-pool-size: 1
    max-pool-size: 20
    max-idle-time-ms: 30_000
    cache:
      cache-1Lvl-enabled: false
      cache-2Lvl-enabled: false

password:
  bcrypt-hash-cost: 15
