jwt:
  issuer: "mybooks.service.auth"
  algorithm: "HS256"
  is-symmetric: true

  # this should be in env of course
  private-key: "strong shared password"
  user-token:
    access:
      expires-in-minutes: 5
    refresh:
      # 8 days: 8*24*60 = 11520
      expires-in-minutes: 11520
  service-token:
    expires-in-seconds: 60

service:
  user:
    jwt:
      issuer: "mybooks.service.user"
  auth:
    discovery:
      base-name: "mybooks.service.auth"
      get-user-token: "/get-user-token"
      refresh-user-token: "/refresh-user-token"

http:
  host: "localhost"
  port: 8097
  err-details-envs:
    - test
    - dev

db:
  mongo:
    db-name: "mybooksAuthDb"
    host: "localhost"
    port: 27017
    min-pool-size: 1
    max-pool-size: 20
    max-idle-time-ms: 30_000
    cache:
      cache-1Lvl-enabled: false
      cache-2Lvl-enabled: false

user-token:
  refresh:
    cleanup-period-min: 5
